=== anatolyageev/Practice7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://nure.ua/Firearms/p7"
        xmlns:tns="http://nure.ua/Firearms/p7">

    <element name="Firearms">
        <complexType>
            <sequence>
                <element name="Gun" type="tns:gun" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="gun">
        <all>
            <element name="Model" type="string"/>
            <element name="Handy" type="tns:handy"/>
            <element name="Origin" type="string"/>
            <element name="performance_characteristics" type="tns:Performance_characteristics"/>
            <element name="Material" type="tns:material"/>
        </all>
    </complexType>

    <complexType name="Performance_characteristics">
        <sequence>
            <element name="range" type="tns:Range"/>
            <element name="target_ange" type="integer"/>
            <element name="clip" type="boolean"/>
            <element name="optician" type="boolean"/>
        </sequence>
    </complexType>

    <complexType name="Range">
        <choice>
            <element name="short_range" type="tns:short_range"/>
            <element name="middle_range" type="tns:middle_range"/>
            <element name="long_range" type="tns:long_range"/>
        </choice>
    </complexType>

    <simpleType name="short_range">
        <restriction base="integer">
            <minInclusive value="0"/>
            <maxInclusive value="499"/>
        </restriction>
    </simpleType>

    <simpleType name="middle_range">
        <restriction base="integer">
            <minInclusive value="500"/>
            <maxInclusive value="999"/>
        </restriction>
    </simpleType>

    <simpleType name="long_range">
            <restriction base="integer">
                <minInclusive value="1000"/>
            </restriction>
    </simpleType>


    <simpleType name="handy">
        <restriction base="string">
            <enumeration value="one-handed"/>
            <enumeration value="two-handed"/>
        </restriction>
    </simpleType>

    <simpleType name="material">
        <restriction base="string">
            <enumeration value="steel"/>
            <enumeration value="composite"/>
        </restriction>
    </simpleType>


</schema>

=== anatolyageev/Practice7/myInput.xml
<?xml version="1.0" encoding="UTF-8"?>
<p7:Firearms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:p7="http://nure.ua/Firearms/p7"
             xsi:schemaLocation="http://nure.ua/Firearms/p7 input.xsd">

    <!--<Firearms>-->
    <Gun>
        <Model>AK-47</Model>
        <Handy>one-handed</Handy>
        <Origin>Russia</Origin>
        <performance_characteristics>
            <range>short</range>
            <target_ange >2000</target_ange>
            <clip>true</clip>
            <optician>true</optician>
        </performance_characteristics>
        <Material>steel</Material>
    </Gun>
    <Gun>
        <Model>M-16</Model>
        <Handy>one-handed</Handy>
        <Origin>USA</Origin>
        <performance_characteristics>
            <range>middle</range>
            <target_ange >3000</target_ange>
            <clip>false</clip>
            <optician>false</optician>
        </performance_characteristics>
        <Material>composite</Material>
    </Gun>
    <Gun>
        <Model>QBZ-95</Model>
        <Handy>two-handed</Handy>
        <Origin>China</Origin>
        <performance_characteristics>
            <range>long</range>
            <target_ange >4000</target_ange>
            <clip>true</clip>
            <optician>true</optician>
        </performance_characteristics>
        <Material>steel</Material>
    </Gun>

</p7:Firearms>

=== anatolyageev/Practice7/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--ь ь ьбб-->

<!--<p7:Firearms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"-->
             <!--xmlns:p7="http://nure.ua/Firearms/p7"-->
             <!--xsi:schemaLocation="http://nure.ua/Firearms/p7 input.xsd">-->

    <Firearms>
    <Gun>
        <Model>AK-47</Model>
        <Handy>one-handed</Handy>
        <Origin>Russia</Origin>
        <performance_characteristics>
            <range cat ="short">300</range>
            <target_ange >2000</target_ange>
            <clip>true</clip>
            <optician>true</optician>
        </performance_characteristics>
        <Material>steel</Material>
    </Gun>
    <Gun>
        <Model>M-16</Model>
        <Handy>one-handed</Handy>
        <Origin>USA</Origin>
        <performance_characteristics>
            <range cat = "middle">600</range>
            <target_ange >3000</target_ange>
            <clip>false</clip>
            <optician>false</optician>
        </performance_characteristics>
        <Material>composite</Material>
    </Gun>
    <Gun>
        <Model>QBZ-95</Model>
        <Handy>two-handed</Handy>
        <Origin>China</Origin>
        <performance_characteristics>
            <range cat ="long">2000</range>
            <target_ange >4000</target_ange>
            <clip>true</clip>
            <optician>true</optician>
        </performance_characteristics>
        <Material>steel</Material>
    </Gun>

    <Gun>
        <Model>QBZ-96</Model>
        <Handy>two-handed</Handy>
        <Origin>China</Origin>
        <performance_characteristics>
            <range cat ="long">3000</range>
            <target_ange >3000</target_ange>
            <clip>true</clip>
            <optician>true</optician>
        </performance_characteristics>
        <Material>steel</Material>
    </Gun>

</Firearms>
<!--</p7:Firearms>-->
        <!--</Firearms>-->
